[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "https://demo.aisolutions.li/*"
  to = "/demo/:splat"
  status = 200

[[redirects]]
  from = "https://waitlist.aisolutions.li/*"
  to = "/waitlist/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
