[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Build settings
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  
  # Required environment variables (set these in Netlify UI)
  # STRIPE_SECRET_KEY = ""
  # STRIPE_WEBHOOK_SECRET = ""
  # PUBLIC_STRIPE_PUBLISHABLE_KEY = ""

[functions]
  # Directory containing Netlify Functions
  directory = "netlify/functions"
  
  # Node.js bundler
  node_bundler = "esbuild"
  
  # External Node modules to exclude from bundling
  external_node_modules = ["stripe"]
  
  # Node version for functions
  node_bridge = true

# Redirect all API requests to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Development server settings
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  framework = "qwik"

[dev.environment]
  # Local development environment variables
  NODE_VERSION = "18"
  
  # Local development Stripe keys (use test keys only)
  # STRIPE_SECRET_KEY = "sk_test_your_test_key_here"
  # PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_your_test_key_here"
  # STRIPE_WEBHOOK_SECRET = "whsec_your_webhook_secret_here"

# Handle SPA routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*.stripe.com; connect-src 'self' https://api.stripe.com; frame-src 'self' https://js.stripe.com https://hooks.stripe.com;"
