[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_TOKEN = "dummy"
  CI = "false"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  framework = "#custom"

[dev.environment]
  # These will be available during local development
  NODE_VERSION = "18"
  # Add your Stripe test keys here for local development
  # In production, set these in Netlify's environment variables
  # STRIPE_PUBLISHABLE_KEY = "pk_test_your_test_publishable_key"
  # STRIPE_SECRET_KEY = "sk_test_your_test_secret_key"
